name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run unit tests
      run: xcodebuild test -scheme SceneBox -workspace SceneBox.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.2' | xcpretty && exit ${PIPESTATUS[0]}
